start-at-login = true

# Mouse follows focus when focused monitor changes (default)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]

    alt-tab = 'workspace-back-and-forth'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-space = 'mode sticky'

[mode.sticky.binding]
    esc = 'mode main'
    alt-space = 'mode main'

    alt-h = ['move left', 'mode main']
    alt-j = ['move down', 'mode main']
    alt-k = ['move up', 'mode main']
    alt-l = ['move right', 'mode main']

    shift-minus = 'resize smart -50'
    shift-equal = 'resize smart +50'

    # In addition to moving the window to given workspace, activate the workspace as well.
    alt-1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9', 'mode main']

    alt-r = ['flatten-workspace-tree', 'mode main']
    alt-f = ['layout floating tiling', 'mode main']

    alt-slash = ['layout tiles horizontal vertical', 'mode main']
    alt-comma = ['layout accordion horizontal vertical', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

