start-at-login = true

# Mouse follows focus when focused monitor changes (default)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 0'

    cmd-backtick = ['focus dfs-next --boundaries-action wrap-around-the-workspace', 'mode main']
    cmd-shift-backtick = ['focus dfs-prev --boundaries-action wrap-around-the-workspace', 'mode main']

    cmd-esc = 'mode lock'

    alt-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9']
    alt-0 = ['move-node-to-workspace 0', 'workspace 0']

    alt-backtick = ['swap dfs-next --wrap-around']
    alt-shift-backtick = ['swap dfs-prev --wrap-around']

    alt-r = 'reload-config'

    alt-tab = 'move-workspace-to-monitor --wrap-around next'

    # On ultra wide monitors, make single windows floating and put them to center with a bit help from old friend, Rectangle app.
    # This is a workaround for widescreen displays until https://github.com/nikitabobko/AeroSpace/issues/60 is implemented.
    alt-f = 'exec-and-forget ~/.config/aerospace/bin/ultrawide.sh'

# escape mode for applying app specific conflicting shortcuts
[mode.lock.binding]

    cmd-esc = ['mode main']
    esc = ['mode main']
