start-at-login = true

# Mouse follows focus when focused monitor changes (default)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    alt-h = ['focus left', 'mode main']
    alt-j = ['focus down', 'mode main']
    alt-k = ['focus up', 'mode main']
    alt-l = ['focus right', 'mode main']

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-space = 'mode prefix'

[mode.prefix.binding]
    alt-space = 'mode main'
    esc = 'mode main'

    h = ['move left', 'mode main']
    j = ['move down', 'mode main']
    k = ['move up', 'mode main']
    l = ['move right', 'mode main']

    alt-h = ['move left', 'mode main']
    alt-j = ['move down', 'mode main']
    alt-k = ['move up', 'mode main']
    alt-l = ['move right', 'mode main']

    minus = ['resize smart -50']
    equal = ['resize smart +50']

    1 = ['workspace 1', 'mode main']
    2 = ['workspace 2', 'mode main']
    3 = ['workspace 3', 'mode main']
    4 = ['workspace 4', 'mode main']
    5 = ['workspace 5', 'mode main']
    6 = ['workspace 6', 'mode main']
    7 = ['workspace 7', 'mode main']
    8 = ['workspace 8', 'mode main']
    9 = ['workspace 9', 'mode main']

    alt-1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9', 'mode main']

    # Rely on Rectangle to resize and center floating windows. This is a workaround
    # to make Aerospace usable on ultra wide monitors.
    f = ['layout floating tiling', 'exec-and-forget open -g "rectangle://execute-action?name=center-half"', 'mode main']
    r = ['reload-config', 'mode main']

    slash = ['layout tiles horizontal vertical', 'mode main']
    comma = ['layout accordion horizontal vertical', 'mode main']
