start-at-login = true

# Mouse follows focus when focused monitor changes (default)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 0'

    cmd-h = ['focus left', 'mode main']
    cmd-j = ['focus down', 'mode main']
    cmd-k = ['focus up', 'mode main']
    cmd-l = ['focus right', 'mode main']

    # On ultra wide monitors, make single windows floating and put them to center with a bit help from old friend, Rectangle app.
    # This is a workaround for widescreen displays until https://github.com/nikitabobko/AeroSpace/issues/60 is implemented.
    cmd-backtick = 'exec-and-forget ~/.config/aerospace/ultrawide.sh'

    # Note: this binding assumes that esc is mapped to caps lock in MacOS settings
    cmd-esc = 'mode esc'

    alt-1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9', 'mode main']
    alt-0 = ['move-node-to-workspace 0', 'workspace 0', 'mode main']

    alt-h = ['move left']
    alt-j = ['move down']
    alt-k = ['move up']
    alt-l = ['move right']

    alt-r = 'reload-config'

# escape mode for applying app specific cmd shortcuts
[mode.esc.binding]

    cmd-esc = ['mode main']
    esc = ['mode main']
