start-at-login = true

# Mouse follows focus when focused monitor changes (default)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    cmd-h = ['focus left']
    cmd-j = ['focus down']
    cmd-k = ['focus up']
    cmd-l = ['focus right']

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 0'

    # Make window floating and put it to center with a bit help from old friend, Rectangle app.
    # This is a workaround for widescreen displays until https://github.com/nikitabobko/AeroSpace/issues/60 is implemented.
    cmd-esc = ['layout floating tiling', 'exec-and-forget open -g "rectangle://execute-action?name=center-half"', 'mode main']

    alt-h = ['move left', 'mode main']
    alt-j = ['move down', 'mode main']
    alt-k = ['move up', 'mode main']
    alt-l = ['move right', 'mode main']

    alt-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9']
    alt-0 = ['move-node-to-workspace 0', 'workspace 0']

    alt-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-esc = ['reload-config', 'mode main']

